/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProposalsRouteImport } from './routes/proposals'
import { Route as AtecOfferRouteImport } from './routes/atec-offer'
import { Route as IndexRouteImport } from './routes/index'

const ProposalsRoute = ProposalsRouteImport.update({
  id: '/proposals',
  path: '/proposals',
  getParentRoute: () => rootRouteImport,
} as any)
const AtecOfferRoute = AtecOfferRouteImport.update({
  id: '/atec-offer',
  path: '/atec-offer',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atec-offer': typeof AtecOfferRoute
  '/proposals': typeof ProposalsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atec-offer': typeof AtecOfferRoute
  '/proposals': typeof ProposalsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atec-offer': typeof AtecOfferRoute
  '/proposals': typeof ProposalsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/atec-offer' | '/proposals'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/atec-offer' | '/proposals'
  id: '__root__' | '/' | '/atec-offer' | '/proposals'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtecOfferRoute: typeof AtecOfferRoute
  ProposalsRoute: typeof ProposalsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/proposals': {
      id: '/proposals'
      path: '/proposals'
      fullPath: '/proposals'
      preLoaderRoute: typeof ProposalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atec-offer': {
      id: '/atec-offer'
      path: '/atec-offer'
      fullPath: '/atec-offer'
      preLoaderRoute: typeof AtecOfferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtecOfferRoute: AtecOfferRoute,
  ProposalsRoute: ProposalsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
